---
version: '3.8'

services:
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./user:/usr/src/app

  movie:
    build:
      context: ./movie
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  show-time:
    build:
      context: ./showtime
      dockerfile: Dockerfile
    ports:
      - "3002:3002"