---
version: '3.8'

services:
  user:
    platform: linux/x86_64
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3004:3004"

  movie:
    build:
      context: ./movie
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  booking:
    platform: linux/x86_64
    build:
      context: ./booking
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
