---
version: '3.8'

services:
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3004:3004"

  movie:
    build:
      context: ./movie
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
