# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eshowtime.proto\"\x07\n\x05\x45mpty\",\n\x0cScheduleData\x12\x0e\n\x06movies\x18\x01 \x03(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"+\n\x08Schedule\x12\x1f\n\x08schedule\x18\x01 \x03(\x0b\x32\r.ScheduleData21\n\x08ShowTime\x12%\n\x0eGetAllSchedule\x12\x06.Empty\x1a\t.Schedule\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showtime_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_EMPTY']._serialized_start = 18
    _globals['_EMPTY']._serialized_end = 25
    _globals['_SCHEDULEDATA']._serialized_start = 27
    _globals['_SCHEDULEDATA']._serialized_end = 71
    _globals['_SCHEDULE']._serialized_start = 73
    _globals['_SCHEDULE']._serialized_end = 116
    _globals['_SHOWTIME']._serialized_start = 118
    _globals['_SHOWTIME']._serialized_end = 167
# @@protoc_insertion_point(module_scope)
