# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import showtime_pb2 as showtime__pb2


class ShowTimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllSchedule = channel.unary_unary(
            '/ShowTime/GetAllSchedule',
            request_serializer=showtime__pb2.Empty.SerializeToString,
            response_deserializer=showtime__pb2.Schedule.FromString,
        )


class ShowTimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetAllSchedule': grpc.unary_unary_rpc_method_handler(
            servicer.GetAllSchedule,
            request_deserializer=showtime__pb2.Empty.FromString,
            response_serializer=showtime__pb2.Schedule.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ShowTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ShowTime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllSchedule(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShowTime/GetAllSchedule',
                                             showtime__pb2.Empty.SerializeToString,
                                             showtime__pb2.Schedule.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
